---
# DEFAULTS
# defaults write com.apple.dock magnification -bool true
- name: "[macdock_defaults] System Preferences > Dock > Magnification: {{ macdock_magnify }}"
  osx_defaults:
    domain: com.apple.dock
    key: magnification
    type: bool
    value: "{{ macdock_magnify }}"
    state: present
  notify: Restart Dock
  tags:
  - macdock
  - macdock_defaults

# defaults write com.apple.dock mineffect -string "scale"
- name: "[macdock_defaults] System Preferences > Dock > Minimize windows using: Scale effect"
  osx_defaults:
    domain: com.apple.dock
    key: mineffect
    type: string
    value: 'scale'
    state: present
  notify: Restart Dock
  tags:
  - macdock
  - macdock_defaults

# defaults write com.apple.dock minimize-to-application -bool true
- name: "[macdock_defaults] System Preferences > Dock > Minimize windows into application icon"
  osx_defaults:
    domain: com.apple.dock
    key: minimize-to-application
    type: bool
    value: true
    state: present
  notify: Restart Dock
  tags:
  - macdock
  - macdock_defaults

# defaults write com.apple.dock autohide -bool false
- name: "[macdock_defaults] System Preferences > Dock > Automatically hide and show the Dock: {{ macdock_hide }}"
  osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: "{{ macdock_hide }}"
    state: present
  notify: Restart Dock
  tags:
  - macdock
  - macdock_defaults

# defaults write com.apple.dock autohide-time-modifier -float 0.5
- name: "[macdock_defaults] System Preferences > Dock > Automatically hide and show the Dock (duration - 0.5)"
  osx_defaults:
    domain: com.apple.dock
    key: autohide-time-modifier
    type: float
    value: 0.5
    state: present
  notify: Restart Dock
  tags:
  - macdock
  - macdock_defaults

# defaults write com.apple.dock autohide-delay -float 0
- name: "[macdock_defaults] System Preferences > Dock > Automatically hide and show the Dock (delay - 0)"
  osx_defaults:
    domain: com.apple.dock
    key: autohide-delay
    type: float
    value: 0
    state: present
  notify: Restart Dock
  tags:
  - macdock
  - macdock_defaults

# defaults write com.apple.dock show-process-indicators -bool true
- name: "[macdock_defaults] System Preferences > Dock > Show indicators for open applications"
  osx_defaults:
    domain: com.apple.dock
    key: show-process-indicators
    type: bool
    value: true
    state: present
  notify: Restart Dock
  tags:
  - macdock
  - macdock_defaults

# defaults write com.apple.dock expose-animation-duration -float 0.12
- name: "[macdock_defaults] Speed up the Mission Control animations"
  osx_defaults:
    domain: com.apple.dock
    key: expose-animation-duration
    type: float
    value: 0.12
    state: present
  notify: Restart Dock
  tags:
  - macdock
  - macdock_defaults
